### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by nolazybits** [MarceloPrado/has-changed-path#2]
Can we use wildcard * in the path like
`packages/**/test/**/*.*` for instance

Thanks

**Comment by MarceloPrado** [comment]
Hi @nolazybits, I believe you could use git diff native functionality for this. Take a look at [this](https://stackoverflow.com/questions/16921787/how-to-enable-wildcard-file-paths-for-git-diff) issue.

Try running `git log -1 --format=format:%H --full-diff -- packages/**/tests` in you repo and see if it returns the latest commit that changed that path.

If it works, I guess I could change the source to use `--` , or you could pass `--` in your path arg.

**Comment by MarceloPrado** [comment]
Hi @nolazybits, did you have the chance to take a look at this? May I close the issue?

**Comment by nolazybits** [comment]
All apologies, I have switched to another task but once back on this I will update you. Please leave it open

**Comment by nolazybits** [comment]
ok checked quickly and it works. so you suggest to pass `-- packages/**/test` in the paths input

**Comment by MarceloPrado** [comment]
Exactly! This will force the action to use the diff functionality I mentioned above.

**Comment by nolazybits** [comment]
Awesome thanks!
This should be added to the doc ;) 
Thanks again!

**Comment by MarceloPrado** [comment]
All set. Just a note, the double dash is not necessary - you can pass directly `packages/**/test`.
